Repository Relay-UMC23/relay-server, pull requests merged in 2023-02, with the labels that each got.

#64 시간표 중복 출력 문제 해결했어요
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
Labels: bug

#58 feat : 달리기 시작 API에 시작 / 끝시간, 목표타입 목표량 추가
  relayRun/src/main/java/com/example/relayRun/record/controller/RunningRecordController.java
  relayRun/src/main/java/com/example/relayRun/record/dto/PostRunningInitRes.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
Labels: enhancement

#73 Fix: 기록이 없는 경우의 속도값 처리
  relayRun/src/main/java/com/example/relayRun/util/RecordDataHandler.java
Labels: bug

#67 Fix: 이메일 인증하기 API
  relayRun/src/main/java/com/example/relayRun/user/controller/UserController.java
  relayRun/src/main/java/com/example/relayRun/user/dto/PostEmailReq.java
  relayRun/src/main/java/com/example/relayRun/user/service/UserService.java
Labels: bug

#74 Feat: 기록 조회 시 목표 종류와 목표 값 반환
  relayRun/src/main/java/com/example/relayRun/club/repository/TimeTableRepository.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetRecordByIdxRes.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
Labels: bug

#78 Issue 68 진행
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubApplyController.java
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/controller/MemberStatusController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PostClubReq.java
  relayRun/src/main/java/com/example/relayRun/club/dto/TimeTableDTO.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
Labels: enhancement

#83 Issue 75: 기록 API 업데이트
  relayRun/src/main/java/com/example/relayRun/club/repository/MemberStatusRepository.java
  relayRun/src/main/java/com/example/relayRun/club/repository/TimeTableRepository.java
  relayRun/src/main/java/com/example/relayRun/record/controller/RunningRecordController.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetCalender.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetCalenderInterface.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetDailyRes.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetRecordByIdxRes.java
  relayRun/src/main/java/com/example/relayRun/record/repository/RunningRecordRepository.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
  relayRun/src/main/java/com/example/relayRun/user/repository/UserProfileRepository.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#69 그룹 삭제 부분 구현
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/entity/ClubEntity.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#48 그룹 정보 변경 API
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubApplyController.java
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PatchClubInfoReq.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PatchClubRecruitStatusReq.java
  relayRun/src/main/java/com/example/relayRun/club/entity/ClubEntity.java
  relayRun/src/main/java/com/example/relayRun/club/entity/TimeTableEntity.java
  relayRun/src/main/java/com/example/relayRun/club/repository/ClubRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
Labels: enhancement

#87 Feat: 메인 페이지
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
Labels: enhancement

#57 방장 위임 API 구현
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/controller/MemberStatusController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PatchHostReq.java
  relayRun/src/main/java/com/example/relayRun/club/repository/MemberStatusRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#84 Issue 72: 자동 프로필 생성 로직 업데이트
  relayRun/src/main/java/com/example/relayRun/user/service/UserService.java
Labels: bug

#96 그룹 관련 조회에서 실시간 달리기 기록과 시간표가 표시되도록 변경하였습니다.
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/controller/MemberStatusController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/GetMemberOfClubRes.java
  relayRun/src/main/java/com/example/relayRun/club/dto/GetTimeTableAndUserProfileRes.java
  relayRun/src/main/java/com/example/relayRun/club/dto/GetTimeTableRes.java
  relayRun/src/main/java/com/example/relayRun/club/repository/ClubRepository.java
  relayRun/src/main/java/com/example/relayRun/club/repository/TimeTableRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
  relayRun/src/main/java/com/example/relayRun/record/dto/GetRecordWithoutLocationRes.java
Labels: bug, enhancement

#98 그룹의 정보 출력 시 모집 상태와 모집정원도 같이 반환
  relayRun/src/main/java/com/example/relayRun/club/dto/GetClubDetailRes.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
Labels: enhancement

#93 Fix: 그룹 신청, 그룹 생성 관련 예외처리 및 transaction
  relayRun/src/main/java/com/example/relayRun/club/controller/MemberStatusController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PostMemberStatusReq.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
  relayRun/src/main/java/com/example/relayRun/user/service/UserProfileService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: bug

#105 Issue 100: Record 테이블에 컬럼 추가
  relayRun/src/main/java/com/example/relayRun/record/entity/RunningRecordEntity.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
Labels: enhancement

#104 Issue 103: 그룹 일별 기록
  relayRun/src/main/java/com/example/relayRun/record/dto/GetDailyRes.java
  relayRun/src/main/java/com/example/relayRun/record/repository/RunningRecordRepository.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
  relayRun/src/main/java/com/example/relayRun/util/RecordDataHandler.java
Labels: bug

#107 Feat : maxNum 상태일 때 recruitStatus 변경
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubApplyController.java
  relayRun/src/main/java/com/example/relayRun/club/entity/ClubEntity.java
  relayRun/src/main/java/com/example/relayRun/club/repository/MemberStatusRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#109 Issue 102: 그룹 이미지 적용
  relayRun/src/main/java/com/example/relayRun/club/controller/ClubController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PostClubReq.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/user/service/UserService.java
Labels: enhancement

#110 Refactor: 시간표 등록 예외처리, 그룹/신청 조회, 그룹 나가기
  relayRun/src/main/java/com/example/relayRun/club/controller/MemberStatusController.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PatchDeleteMemberReq.java
  relayRun/src/main/java/com/example/relayRun/club/dto/PostTimeTableReq.java
  relayRun/src/main/java/com/example/relayRun/club/repository/ClubRepository.java
  relayRun/src/main/java/com/example/relayRun/club/repository/MemberStatusRepository.java
  relayRun/src/main/java/com/example/relayRun/club/repository/TimeTableRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#111 Feat notify time to run
  .github/workflows/CICD.yml
  relayRun/.gitignore
  relayRun/build.gradle
  relayRun/src/main/java/com/example/relayRun/RelayRunApplication.java
  relayRun/src/main/java/com/example/relayRun/club/repository/TimeTableRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/ClubService.java
  relayRun/src/main/java/com/example/relayRun/config/CustomSchedulingConfig.java
  relayRun/src/main/java/com/example/relayRun/event/BatonTouchEvent.java
  relayRun/src/main/java/com/example/relayRun/event/NotifyEventPublisher.java
  relayRun/src/main/java/com/example/relayRun/event/TimeToRunEvent.java
  relayRun/src/main/java/com/example/relayRun/fcm/controller/FCMController.java
  relayRun/src/main/java/com/example/relayRun/fcm/controller/FCMEventController.java
  relayRun/src/main/java/com/example/relayRun/fcm/dto/NotificationMessage.java
  relayRun/src/main/java/com/example/relayRun/fcm/dto/PostDeviceReq.java
  relayRun/src/main/java/com/example/relayRun/fcm/dto/PostDeviceRes.java
  relayRun/src/main/java/com/example/relayRun/fcm/entity/UserDeviceEntity.java
  relayRun/src/main/java/com/example/relayRun/fcm/repository/UserDeviceRepository.java
  relayRun/src/main/java/com/example/relayRun/fcm/service/FCMSenderSerivce.java
  relayRun/src/main/java/com/example/relayRun/fcm/service/FCMService.java
  relayRun/src/main/java/com/example/relayRun/record/entity/RunningRecordEntity.java
  relayRun/src/main/java/com/example/relayRun/record/service/RunningRecordService.java
  relayRun/src/main/java/com/example/relayRun/schedule/ScheduleService.java
  relayRun/src/main/java/com/example/relayRun/schedule/task/NotifyToRunTask.java
  relayRun/src/main/java/com/example/relayRun/user/controller/UserController.java
  relayRun/src/main/java/com/example/relayRun/user/entity/UserEntity.java
  relayRun/src/main/java/com/example/relayRun/user/repository/UserRepository.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
  relayRun/src/main/java/com/example/relayRun/util/RecordDataHandler.java
  relayRun/src/main/resources/application.yml
Labels: enhancement

#115 Feat: 방장이 그룹을 나가려 할 때 예외처리
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
  relayRun/src/main/java/com/example/relayRun/util/BaseResponseStatus.java
Labels: enhancement

#116 Fix: 그룹 모집완료 변경
  relayRun/src/main/java/com/example/relayRun/club/repository/MemberStatusRepository.java
  relayRun/src/main/java/com/example/relayRun/club/service/MemberStatusService.java
Labels: bug
